-- Lots UN CAHIER LE GRAND JOURNAL
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-05-28 10:22:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 16h22 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-05-28 14:30:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 20h30 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-05-29 06:30:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 36h30 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-05-30 07:06:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 61h6 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-05-30 13:34:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 67h34 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-03 04:29:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 154h29 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-03 14:29:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 164h29 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-06 13:28:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 235h28 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-08 09:11:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 279h11 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-09 01:15:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 295h15 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-09 07:03:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 301h3 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-09 13:10:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 307h10 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-09 19:52:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 313h52 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-10 01:14:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 319h14 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-10 15:52:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 333h52 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-13 07:10:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 397h10 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-14 20:35:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 434h35 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-15 01:10:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 439h10 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-15 14:56:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 452h56 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-16 06:44:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 468h44 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-16 18:10:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 480h10 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-17 14:33:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 500h33 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-18 20:33:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 530h33 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-19 18:11:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 552h11 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-20 16:43:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 574h43 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-21 22:02:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 604h2 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-22 01:37:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 607h37 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-23 09:42:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 639h42 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-23 10:07:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 640h7 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-23 12:52:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 642h52 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-24 10:47:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 664h47 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-24 11:58:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 665h58 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-24 17:28:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 671h28 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-25 02:55:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 680h55 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-26 22:32:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 724h32 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-27 22:10:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 748h10 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-28 04:22:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 754h22 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-06-30 22:11:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 820h11 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-07-01 11:55:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 833h55 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-07-03 15:07:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 885h7 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-07-04 04:37:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 898h37 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-07-05 18:48:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 936h48 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-07-06 00:35:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 942h35 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-07-06 01:50:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 943h50 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-07-06 10:09:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 952h9 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-07-06 21:42:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 963h42 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-07-08 16:27:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 1006h27 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-07-10 11:16:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 1049h16 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-07-10 21:16:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 1059h16 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (1,convert(datetime , '2014-07-11 15:47:00:00' , 21),0 ,'UN CAHIER LE GRAND JOURNAL','blason-LGJ',NULL,NULL); -- 1077h47 de plus


-- Lots UN CAHIER CANAL+ SERIES
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-05-28 05:26:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 11h26 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-05-30 00:41:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 54h41 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-05-30 02:58:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 56h58 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-05-31 20:08:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 98h8 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-02 09:45:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 135h45 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-03 21:50:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 171h50 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-04 09:28:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 183h28 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-06 03:21:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 225h21 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-06 20:59:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 242h59 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-08 17:36:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 287h36 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-09 04:55:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 298h55 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-10 02:02:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 320h2 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-10 08:52:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 326h52 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-10 11:00:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 329h0 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-10 11:37:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 329h37 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-11 15:12:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 357h12 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-13 06:22:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 396h22 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-13 09:58:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 399h58 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-13 12:43:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 402h43 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-14 02:27:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 416h27 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-14 09:00:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 423h0 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-15 18:39:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 456h39 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-16 07:37:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 469h37 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-17 09:54:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 495h54 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-17 19:55:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 505h55 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-18 02:27:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 512h27 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-20 13:28:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 571h28 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-22 20:14:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 626h14 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-24 13:16:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 667h16 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-25 16:19:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 694h19 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-26 02:35:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 704h35 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-06-29 17:35:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 791h35 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-01 00:23:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 822h23 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-02 02:06:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 848h6 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-02 02:35:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 848h35 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-02 20:38:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 866h38 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-03 05:56:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 875h56 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-03 14:48:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 884h48 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-03 19:49:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 889h49 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-04 11:54:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 905h54 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-05 09:28:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 927h28 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-07 04:50:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 970h50 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-07 05:18:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 971h18 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-07 22:35:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 988h35 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-08 09:00:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 999h0 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-09 00:34:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 1014h34 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-10 01:23:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 1039h23 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-10 13:59:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 1051h59 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-11 13:16:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 1075h16 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (2,convert(datetime , '2014-07-11 15:30:00:00' , 21),0 ,'UN CAHIER CANAL+ SERIES','blason-creationoriginale',NULL,NULL); -- 1077h30 de plus


-- Lots UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-05-28 09:07:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 15h7 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-05-28 11:46:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 17h46 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-05-29 06:42:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 36h42 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-05-30 12:05:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 66h5 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-05-30 14:06:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 68h6 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-05-31 00:43:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 78h43 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-05-31 04:41:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 82h41 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-05-31 12:23:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 90h23 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-04 11:23:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 185h23 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-06 09:44:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 231h44 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-07 18:14:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 264h14 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-09 07:24:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 301h24 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-09 15:07:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 309h7 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-09 16:04:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 310h4 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-10 16:01:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 334h1 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-10 22:47:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 340h47 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-11 06:12:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 348h12 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-12 19:26:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 385h26 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-13 01:18:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 391h18 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-14 00:20:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 414h20 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-15 07:14:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 445h14 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-15 18:27:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 456h27 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-17 06:46:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 492h46 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-17 14:37:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 500h37 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-17 17:12:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 503h12 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-17 18:00:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 504h0 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-18 04:27:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 514h27 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-19 09:34:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 543h34 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-20 02:50:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 560h50 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-20 09:10:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 567h10 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-20 11:46:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 569h46 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-21 13:33:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 595h33 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-21 15:04:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 597h4 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-21 23:37:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 605h37 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-23 00:04:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 630h4 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-24 18:08:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 672h8 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-25 04:57:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 682h57 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-25 22:07:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 700h7 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-26 07:57:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 709h57 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-26 23:53:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 725h53 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-28 17:26:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 767h26 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-29 08:01:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 782h1 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-06-29 11:34:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 785h34 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-07-01 09:07:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 831h7 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-07-01 15:31:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 837h31 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-07-03 00:31:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 870h31 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-07-06 14:12:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 956h12 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-07-07 16:08:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 982h8 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-07-07 17:59:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 983h59 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (3,convert(datetime , '2014-07-10 23:24:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION CANAL+ POUR IPHONE 4','blason-iphone',NULL,NULL); -- 1061h24 de plus


-- Lots UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-05-29 09:23:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 39h23 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-05-29 23:56:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 53h56 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-05-31 05:58:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 83h58 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-05-31 13:33:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 91h33 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-05-31 15:53:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 93h53 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-05-31 16:31:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 94h31 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-06-01 11:26:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 113h26 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-06-01 22:42:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 124h42 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-06-06 02:34:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 224h34 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-06-15 19:48:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 457h48 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-06-16 05:41:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 467h41 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-06-16 06:10:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 468h10 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-06-18 01:20:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 511h20 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-06-20 11:40:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 569h40 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-06-22 13:34:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 619h34 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-06-23 04:18:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 634h18 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-06-26 04:12:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 706h12 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-06-26 11:56:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 713h56 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-06-30 05:18:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 803h18 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-06-30 20:13:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 818h13 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-07-01 07:56:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 829h56 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-07-04 23:47:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 917h47 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-07-07 00:48:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 966h48 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-07-07 16:05:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 982h5 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (4,convert(datetime , '2014-07-10 12:36:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 4','blason-lpj4',NULL,NULL); -- 1050h36 de plus


-- Lots UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-05-28 06:54:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 12h54 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-05-29 02:30:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 32h30 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-06-09 02:47:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 296h47 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-06-09 09:22:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 303h22 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-06-11 05:35:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 347h35 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-06-11 05:50:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 347h50 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-06-11 21:02:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 363h2 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-06-11 22:54:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 364h54 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-06-14 18:08:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 432h8 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-06-21 08:41:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 590h41 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-06-21 19:05:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 601h5 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-06-21 19:51:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 601h51 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-06-21 22:30:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 604h30 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-06-22 07:57:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 613h57 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-06-23 12:44:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 642h44 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-06-27 05:38:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 731h38 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-06-27 16:03:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 742h3 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-06-28 08:48:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 758h48 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-06-29 17:08:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 791h8 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-07-05 14:59:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 932h59 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-07-06 17:42:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 959h42 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-07-07 11:26:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 977h26 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-07-09 12:08:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 1026h8 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-07-10 18:56:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 1056h56 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (5,convert(datetime , '2014-07-11 04:08:00:00' , 21),0 ,'UNE COQUE IPHONE VERSION LE PETIT JOURNAL  POUR IPHONE 5','blason-lpj5',NULL,NULL); -- 1066h8 de plus


-- Lots UN PARAPLUIE PLIANT DE COULEUR VIOLET
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (6,convert(datetime , '2014-05-29 21:29:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR VIOLET','blason-parapluieViolet',NULL,NULL); -- 51h29 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (6,convert(datetime , '2014-06-01 07:26:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR VIOLET','blason-parapluieViolet',NULL,NULL); -- 109h26 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (6,convert(datetime , '2014-06-05 16:48:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR VIOLET','blason-parapluieViolet',NULL,NULL); -- 214h48 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (6,convert(datetime , '2014-06-15 21:59:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR VIOLET','blason-parapluieViolet',NULL,NULL); -- 459h59 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (6,convert(datetime , '2014-06-17 19:25:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR VIOLET','blason-parapluieViolet',NULL,NULL); -- 505h25 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (6,convert(datetime , '2014-06-20 11:41:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR VIOLET','blason-parapluieViolet',NULL,NULL); -- 569h41 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (6,convert(datetime , '2014-06-23 02:00:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR VIOLET','blason-parapluieViolet',NULL,NULL); -- 632h0 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (6,convert(datetime , '2014-06-23 17:21:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR VIOLET','blason-parapluieViolet',NULL,NULL); -- 647h21 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (6,convert(datetime , '2014-06-25 02:21:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR VIOLET','blason-parapluieViolet',NULL,NULL); -- 680h21 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (6,convert(datetime , '2014-06-28 14:17:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR VIOLET','blason-parapluieViolet',NULL,NULL); -- 764h17 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (6,convert(datetime , '2014-07-01 08:22:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR VIOLET','blason-parapluieViolet',NULL,NULL); -- 830h22 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (6,convert(datetime , '2014-07-02 13:19:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR VIOLET','blason-parapluieViolet',NULL,NULL); -- 859h19 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (6,convert(datetime , '2014-07-04 23:20:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR VIOLET','blason-parapluieViolet',NULL,NULL); -- 917h20 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (6,convert(datetime , '2014-07-05 03:25:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR VIOLET','blason-parapluieViolet',NULL,NULL); -- 921h25 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (6,convert(datetime , '2014-07-05 10:34:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR VIOLET','blason-parapluieViolet',NULL,NULL); -- 928h34 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (6,convert(datetime , '2014-07-08 05:55:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR VIOLET','blason-parapluieViolet',NULL,NULL); -- 995h55 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (6,convert(datetime , '2014-07-08 11:11:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR VIOLET','blason-parapluieViolet',NULL,NULL); -- 1001h11 de plus


-- Lots UN PARAPLUIE PLIANT DE COULEUR ORANGE
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (7,convert(datetime , '2014-05-29 03:49:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR ORANGE','blason-parapluieOrange',NULL,NULL); -- 33h49 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (7,convert(datetime , '2014-05-29 14:30:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR ORANGE','blason-parapluieOrange',NULL,NULL); -- 44h30 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (7,convert(datetime , '2014-06-07 08:01:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR ORANGE','blason-parapluieOrange',NULL,NULL); -- 254h1 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (7,convert(datetime , '2014-06-08 05:01:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR ORANGE','blason-parapluieOrange',NULL,NULL); -- 275h1 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (7,convert(datetime , '2014-06-10 23:19:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR ORANGE','blason-parapluieOrange',NULL,NULL); -- 341h19 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (7,convert(datetime , '2014-06-20 14:47:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR ORANGE','blason-parapluieOrange',NULL,NULL); -- 572h47 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (7,convert(datetime , '2014-06-22 07:53:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR ORANGE','blason-parapluieOrange',NULL,NULL); -- 613h53 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (7,convert(datetime , '2014-06-22 12:29:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR ORANGE','blason-parapluieOrange',NULL,NULL); -- 618h29 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (7,convert(datetime , '2014-06-22 15:25:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR ORANGE','blason-parapluieOrange',NULL,NULL); -- 621h25 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (7,convert(datetime , '2014-06-22 17:30:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR ORANGE','blason-parapluieOrange',NULL,NULL); -- 623h30 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (7,convert(datetime , '2014-06-23 12:37:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR ORANGE','blason-parapluieOrange',NULL,NULL); -- 642h37 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (7,convert(datetime , '2014-06-30 08:08:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR ORANGE','blason-parapluieOrange',NULL,NULL); -- 806h8 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (7,convert(datetime , '2014-07-01 15:08:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR ORANGE','blason-parapluieOrange',NULL,NULL); -- 837h8 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (7,convert(datetime , '2014-07-02 11:05:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR ORANGE','blason-parapluieOrange',NULL,NULL); -- 857h5 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (7,convert(datetime , '2014-07-06 14:58:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR ORANGE','blason-parapluieOrange',NULL,NULL); -- 956h58 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (7,convert(datetime , '2014-07-10 13:11:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR ORANGE','blason-parapluieOrange',NULL,NULL); -- 1051h11 de plus


-- Lots UN PARAPLUIE PLIANT DE COULEUR  NOIR
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (8,convert(datetime , '2014-05-30 19:41:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR  NOIR','blason-parapluieNoir',NULL,NULL); -- 73h41 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (8,convert(datetime , '2014-05-31 04:00:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR  NOIR','blason-parapluieNoir',NULL,NULL); -- 82h0 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (8,convert(datetime , '2014-05-31 07:17:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR  NOIR','blason-parapluieNoir',NULL,NULL); -- 85h17 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (8,convert(datetime , '2014-05-31 19:35:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR  NOIR','blason-parapluieNoir',NULL,NULL); -- 97h35 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (8,convert(datetime , '2014-06-01 09:28:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR  NOIR','blason-parapluieNoir',NULL,NULL); -- 111h28 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (8,convert(datetime , '2014-06-06 04:34:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR  NOIR','blason-parapluieNoir',NULL,NULL); -- 226h34 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (8,convert(datetime , '2014-06-10 09:42:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR  NOIR','blason-parapluieNoir',NULL,NULL); -- 327h42 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (8,convert(datetime , '2014-06-10 10:35:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR  NOIR','blason-parapluieNoir',NULL,NULL); -- 328h35 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (8,convert(datetime , '2014-06-12 04:25:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR  NOIR','blason-parapluieNoir',NULL,NULL); -- 370h25 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (8,convert(datetime , '2014-06-18 11:36:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR  NOIR','blason-parapluieNoir',NULL,NULL); -- 521h36 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (8,convert(datetime , '2014-06-25 07:08:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR  NOIR','blason-parapluieNoir',NULL,NULL); -- 685h8 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (8,convert(datetime , '2014-06-26 01:00:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR  NOIR','blason-parapluieNoir',NULL,NULL); -- 703h0 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (8,convert(datetime , '2014-06-28 17:09:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR  NOIR','blason-parapluieNoir',NULL,NULL); -- 767h9 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (8,convert(datetime , '2014-06-30 12:26:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR  NOIR','blason-parapluieNoir',NULL,NULL); -- 810h26 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (8,convert(datetime , '2014-07-03 05:11:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR  NOIR','blason-parapluieNoir',NULL,NULL); -- 875h11 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (8,convert(datetime , '2014-07-05 07:58:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR  NOIR','blason-parapluieNoir',NULL,NULL); -- 925h58 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (8,convert(datetime , '2014-07-07 01:34:00:00' , 21),0 ,'UN PARAPLUIE PLIANT DE COULEUR  NOIR','blason-parapluieNoir',NULL,NULL); -- 967h34 de plus


-- Lots UN MUG GROLAND
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-05-29 03:28:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 33h28 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-05-30 05:14:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 59h14 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-06-01 16:34:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 118h34 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-06-06 18:51:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 240h51 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-06-08 15:58:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 285h58 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-06-08 22:50:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 292h50 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-06-09 04:11:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 298h11 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-06-09 14:46:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 308h46 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-06-09 21:40:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 315h40 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-06-10 04:42:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 322h42 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-06-14 08:15:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 422h15 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-06-19 00:12:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 534h12 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-06-20 18:01:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 576h1 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-06-23 16:32:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 646h32 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-06-26 18:55:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 720h55 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-06-27 07:50:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 733h50 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-06-27 20:39:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 746h39 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-06-28 11:02:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 761h2 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-06-30 08:24:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 806h24 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-07-02 19:38:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 865h38 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-07-07 01:05:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 967h5 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-07-07 03:30:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 969h30 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-07-08 17:08:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 1007h8 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-07-08 23:01:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 1013h1 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (9,convert(datetime , '2014-07-10 06:25:00:00' , 21),0 ,'UN MUG GROLAND','blason-muggroland',NULL,NULL); -- 1044h25 de plus


-- Lots UN MUG LE GRAND JOURNAL
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-05-30 02:29:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 56h29 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-05-31 00:00:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 78h0 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-06-04 11:34:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 185h34 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-06-04 17:08:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 191h8 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-06-06 11:45:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 233h45 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-06-07 05:52:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 251h52 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-06-07 22:28:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 268h28 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-06-09 01:47:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 295h47 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-06-13 11:26:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 401h26 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-06-14 02:03:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 416h3 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-06-18 15:55:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 525h55 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-06-18 17:36:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 527h36 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-06-19 12:07:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 546h7 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-06-19 23:10:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 557h10 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-06-22 02:20:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 608h20 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-06-23 01:03:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 631h3 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-06-28 05:08:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 755h8 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-06-28 17:54:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 767h54 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-07-03 01:42:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 871h42 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-07-03 21:35:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 891h35 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-07-04 18:49:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 912h49 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-07-07 01:37:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 967h37 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-07-10 02:07:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 1040h7 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-07-10 06:12:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 1044h12 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (10,convert(datetime , '2014-07-11 13:41:00:00' , 21),0 ,'UN MUG LE GRAND JOURNAL','blason-mugGJ',NULL,NULL); -- 1075h41 de plus


-- Lots UN CARNET CINEMA
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (11,convert(datetime , '2014-06-03 14:56:00:00' , 21),0 ,'UN CARNET CINEMA','blason-carnetcine',NULL,NULL); -- 164h56 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (11,convert(datetime , '2014-06-03 21:36:00:00' , 21),0 ,'UN CARNET CINEMA','blason-carnetcine',NULL,NULL); -- 171h36 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (11,convert(datetime , '2014-06-04 20:54:00:00' , 21),0 ,'UN CARNET CINEMA','blason-carnetcine',NULL,NULL); -- 194h54 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (11,convert(datetime , '2014-06-18 02:15:00:00' , 21),0 ,'UN CARNET CINEMA','blason-carnetcine',NULL,NULL); -- 512h15 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (11,convert(datetime , '2014-06-18 03:34:00:00' , 21),0 ,'UN CARNET CINEMA','blason-carnetcine',NULL,NULL); -- 513h34 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (11,convert(datetime , '2014-06-20 01:32:00:00' , 21),0 ,'UN CARNET CINEMA','blason-carnetcine',NULL,NULL); -- 559h32 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (11,convert(datetime , '2014-06-24 18:37:00:00' , 21),0 ,'UN CARNET CINEMA','blason-carnetcine',NULL,NULL); -- 672h37 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (11,convert(datetime , '2014-06-25 08:24:00:00' , 21),0 ,'UN CARNET CINEMA','blason-carnetcine',NULL,NULL); -- 686h24 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (11,convert(datetime , '2014-06-30 15:37:00:00' , 21),0 ,'UN CARNET CINEMA','blason-carnetcine',NULL,NULL); -- 813h37 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (11,convert(datetime , '2014-07-07 10:07:00:00' , 21),0 ,'UN CARNET CINEMA','blason-carnetcine',NULL,NULL); -- 976h7 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (11,convert(datetime , '2014-07-07 14:25:00:00' , 21),0 ,'UN CARNET CINEMA','blason-carnetcine',NULL,NULL); -- 980h25 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (11,convert(datetime , '2014-07-08 07:47:00:00' , 21),0 ,'UN CARNET CINEMA','blason-carnetcine',NULL,NULL); -- 997h47 de plus


-- Lots UN CARNET SPORT
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (12,convert(datetime , '2014-05-28 23:55:00:00' , 21),0 ,'UN CARNET SPORT','blason-sport',NULL,NULL); -- 29h55 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (12,convert(datetime , '2014-06-01 10:35:00:00' , 21),0 ,'UN CARNET SPORT','blason-sport',NULL,NULL); -- 112h35 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (12,convert(datetime , '2014-06-03 22:43:00:00' , 21),0 ,'UN CARNET SPORT','blason-sport',NULL,NULL); -- 172h43 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (12,convert(datetime , '2014-06-06 19:43:00:00' , 21),0 ,'UN CARNET SPORT','blason-sport',NULL,NULL); -- 241h43 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (12,convert(datetime , '2014-06-07 06:00:00:00' , 21),0 ,'UN CARNET SPORT','blason-sport',NULL,NULL); -- 252h0 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (12,convert(datetime , '2014-06-11 03:33:00:00' , 21),0 ,'UN CARNET SPORT','blason-sport',NULL,NULL); -- 345h33 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (12,convert(datetime , '2014-06-11 06:39:00:00' , 21),0 ,'UN CARNET SPORT','blason-sport',NULL,NULL); -- 348h39 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (12,convert(datetime , '2014-06-17 23:10:00:00' , 21),0 ,'UN CARNET SPORT','blason-sport',NULL,NULL); -- 509h10 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (12,convert(datetime , '2014-06-27 12:07:00:00' , 21),0 ,'UN CARNET SPORT','blason-sport',NULL,NULL); -- 738h7 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (12,convert(datetime , '2014-07-02 22:02:00:00' , 21),0 ,'UN CARNET SPORT','blason-sport',NULL,NULL); -- 868h2 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (12,convert(datetime , '2014-07-06 07:54:00:00' , 21),0 ,'UN CARNET SPORT','blason-sport',NULL,NULL); -- 949h54 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (12,convert(datetime , '2014-07-09 11:02:00:00' , 21),0 ,'UN CARNET SPORT','blason-sport',NULL,NULL); -- 1025h2 de plus


-- Lots UN CARNET CANAL+
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (13,convert(datetime , '2014-06-02 01:18:00:00' , 21),0 ,'UN CARNET CANAL+','blason-carnetcanal',NULL,NULL); -- 127h18 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (13,convert(datetime , '2014-06-06 09:07:00:00' , 21),0 ,'UN CARNET CANAL+','blason-carnetcanal',NULL,NULL); -- 231h7 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (13,convert(datetime , '2014-06-06 18:39:00:00' , 21),0 ,'UN CARNET CANAL+','blason-carnetcanal',NULL,NULL); -- 240h39 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (13,convert(datetime , '2014-06-21 20:58:00:00' , 21),0 ,'UN CARNET CANAL+','blason-carnetcanal',NULL,NULL); -- 602h58 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (13,convert(datetime , '2014-06-25 20:37:00:00' , 21),0 ,'UN CARNET CANAL+','blason-carnetcanal',NULL,NULL); -- 698h37 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (13,convert(datetime , '2014-06-26 12:19:00:00' , 21),0 ,'UN CARNET CANAL+','blason-carnetcanal',NULL,NULL); -- 714h19 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (13,convert(datetime , '2014-06-27 09:45:00:00' , 21),0 ,'UN CARNET CANAL+','blason-carnetcanal',NULL,NULL); -- 735h45 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (13,convert(datetime , '2014-07-01 09:35:00:00' , 21),0 ,'UN CARNET CANAL+','blason-carnetcanal',NULL,NULL); -- 831h35 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (13,convert(datetime , '2014-07-05 17:01:00:00' , 21),0 ,'UN CARNET CANAL+','blason-carnetcanal',NULL,NULL); -- 935h1 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (13,convert(datetime , '2014-07-07 05:23:00:00' , 21),0 ,'UN CARNET CANAL+','blason-carnetcanal',NULL,NULL); -- 971h23 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (13,convert(datetime , '2014-07-08 13:24:00:00' , 21),0 ,'UN CARNET CANAL+','blason-carnetcanal',NULL,NULL); -- 1003h24 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (13,convert(datetime , '2014-07-11 04:34:00:00' , 21),0 ,'UN CARNET CANAL+','blason-carnetcanal',NULL,NULL); -- 1066h34 de plus


-- Lots UN CARNET LE PETIT JOURNAL
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (14,convert(datetime , '2014-05-28 08:03:00:00' , 21),0 ,'UN CARNET LE PETIT JOURNAL','blason-carnetLPJ',NULL,NULL); -- 14h3 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (14,convert(datetime , '2014-05-31 18:53:00:00' , 21),0 ,'UN CARNET LE PETIT JOURNAL','blason-carnetLPJ',NULL,NULL); -- 96h53 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (14,convert(datetime , '2014-06-03 11:14:00:00' , 21),0 ,'UN CARNET LE PETIT JOURNAL','blason-carnetLPJ',NULL,NULL); -- 161h14 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (14,convert(datetime , '2014-06-08 19:26:00:00' , 21),0 ,'UN CARNET LE PETIT JOURNAL','blason-carnetLPJ',NULL,NULL); -- 289h26 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (14,convert(datetime , '2014-06-12 18:27:00:00' , 21),0 ,'UN CARNET LE PETIT JOURNAL','blason-carnetLPJ',NULL,NULL); -- 384h27 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (14,convert(datetime , '2014-06-13 05:21:00:00' , 21),0 ,'UN CARNET LE PETIT JOURNAL','blason-carnetLPJ',NULL,NULL); -- 395h21 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (14,convert(datetime , '2014-06-15 12:03:00:00' , 21),0 ,'UN CARNET LE PETIT JOURNAL','blason-carnetLPJ',NULL,NULL); -- 450h3 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (14,convert(datetime , '2014-06-17 12:15:00:00' , 21),0 ,'UN CARNET LE PETIT JOURNAL','blason-carnetLPJ',NULL,NULL); -- 498h15 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (14,convert(datetime , '2014-06-20 02:15:00:00' , 21),0 ,'UN CARNET LE PETIT JOURNAL','blason-carnetLPJ',NULL,NULL); -- 560h15 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (14,convert(datetime , '2014-06-20 05:26:00:00' , 21),0 ,'UN CARNET LE PETIT JOURNAL','blason-carnetLPJ',NULL,NULL); -- 563h26 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (14,convert(datetime , '2014-06-20 17:36:00:00' , 21),0 ,'UN CARNET LE PETIT JOURNAL','blason-carnetLPJ',NULL,NULL); -- 575h36 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (14,convert(datetime , '2014-06-24 05:13:00:00' , 21),0 ,'UN CARNET LE PETIT JOURNAL','blason-carnetLPJ',NULL,NULL); -- 659h13 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (14,convert(datetime , '2014-06-30 14:26:00:00' , 21),0 ,'UN CARNET LE PETIT JOURNAL','blason-carnetLPJ',NULL,NULL); -- 812h26 de plus
INSERT INTO dbo.InstantGagnants ([LotId], [StartDateTime],[Won],[Label],[FrontHtmlId],[UserId],[WonDate]) VALUES (14,convert(datetime , '2014-07-03 04:42:00:00' , 21),0 ,'UN CARNET LE PETIT JOURNAL','blason-carnetLPJ',NULL,NULL); -- 874h42 de plus


