//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetrieveZipCodes
{
    using System;
    using System.Collections.Generic;
    
    public partial class insee
    {
        public string Commune { get; set; }
        public string Codepos { get; set; }
        public string Departement { get; set; }
        public string INSEE1 { get; set; }
    }
}
