// <auto-generated />
namespace Collecte.DAL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Test));
        
        string IMigrationMetadata.Id
        {
            get { return "201406040817335_Test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
